FROM python:3.12

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /backend

COPY requirements.txt .
RUN pip install --upgrade pip &&  pip install --no-cache-dir -r requirements.txt
   
COPY . .

EXPOSE 8000

