# Generated by Django 5.2.7 on 2025-11-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_page_contenttype_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
