# Generated by Django 5.2.7 on 2025-11-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_content_content_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng', models.TextField()),
                ('swe', models.TextField()),
            ],
        ),
    ]
