# Generated by Django 5.2.7 on 2025-11-01 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_terms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terms',
            options={'verbose_name_plural': 'Terms'},
        ),
    ]
