# Generated by Django 5.2.7 on 2025-11-01 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_terms_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenttype',
            name='page',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
