# Generated by Django 5.2.7 on 2025-11-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_contenttype_page_delete_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('article_num', models.CharField(max_length=50)),
                ('in_price', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(max_length=50)),
                ('in_stock', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
            ],
        ),
    ]
